### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [HectorAnadon/Face-expression-and-ethnic-recognition#1]
can you please share the pretrained model?

**Comment by HectorAnadon** [comment]
WEIGHTS_PATH = 'https://github.com/rcmalli/keras-vggface/releases/download/v2.0/rcmalli_vggface_tf_v2.h5'
WEIGHTS_PATH_NO_TOP = 'https://github.com/rcmalli/keras-vggface/releases/download/v2.0/rcmalli_vggface_tf_notop_v2.h5'

The repo can be found https://github.com/rcmalli/keras-vggface

**Comment by QBoney** [comment]
These files no longer exist.
