### ISSUE TITLE
Error in face_network.py

### ISSUE THREAD

**Issue by smartkidyn** [HectorAnadon/Face-expression-and-ethnic-recognition#12]
Hi,

I'm new to python so forgive any ignorance. I am using tensorflow 2.1.1 and kerras 2.3.1 and can't run the lines:

from keras.engine import Model
from keras.layers import Flatten, Dense, Input

Any idea why this might be?

**Comment by HectorAnadon** [comment]
Hello!
This is an old project, you should try Keras==2.0.8
