### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by atefm** [HectorAnadon/Face-expression-and-ethnic-recognition#2]
Can you please share the following files:

images.h5
means_ethnic.npy
weights_ethnic.hdf5

**Comment by HectorAnadon** [comment]
You can generate images.h5 with:

> $ python read_images.py
> $ python read_emotions.py

Te dataset can be found [here](http://www.psychophysiolab.com/msfde/terms.php).
You can download the other files [here](https://www.dropbox.com/sh/5loojypio177qcn/AACF0T2YBHt8Uv9KoIFhX3Pfa?dl=0).
