### ISSUE TITLE
Support Files

### ISSUE THREAD

**Issue by patrickl086** [HectorAnadon/Face-expression-and-ethnic-recognition#6]
Hello, 

Can you please share the following files:
means_ethnic.npy
weights_ethnic.hdf5

**Comment by HectorAnadon** [comment]
https://www.dropbox.com/home/Face-expression-and-ethnic-recognition

**Comment by patrickl086** [comment]
Thanks a lot Hector!



________________________________
De: Hector Anadon <notifications@github.com>
Enviado: martes, 30 de octubre de 2018 03:03 a. m.
Para: HectorAnadon/Face-expression-and-ethnic-recognition
CC: patrickl086; Author
Asunto: Re: [HectorAnadon/Face-expression-and-ethnic-recognition] Support Files (#6)


https://www.dropbox.com/home/Face-expression-and-ethnic-recognition
