### ISSUE TITLE
Can you fix the pre-trained model download link.

### ISSUE THREAD

**Issue by sudheer-palaparambil** [HectorAnadon/Face-expression-and-ethnic-recognition#8]
Hi,

     I just want to run the test scripts, but the pre-trained models download link is not working. Can you please fix it.

    Thanks and regards.

Vishal

**Comment by HectorAnadon** [comment]
It should work now. Sorry for the wrong link before. It should be this one https://www.dropbox.com/sh/5loojypio177qcn/AACF0T2YBHt8Uv9KoIFhX3Pfa?dl=0.

**Comment by sudheer-palaparambil** [comment]
Thank you.
